import * as React from 'react';
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import SessionAuthProvider from "@/context/SessionAuthProvider";
import type { Metadata } from "next";
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import Typography from '@mui/material/Typography';
import Toolbar from '@mui/material/Toolbar';
import AppBar from '@mui/material/AppBar';
import '@/styles/styles.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionAuthProvider>
                <Grid container component="main" sx={{maxHeight: '100vh'}} >
                    <Box sx={{ flexGrow: 1 }}>
                        <AppBar style={{ backgroundColor: '#0A233F' }} position="static">
                            <Toolbar>
                                <Typography  variant="h6" component="div" sx={{ flexGrow: 1 }}>
                                    <span className='invierte' style={{ fontWeight: 400 }}>UNITED</span> <span className='invierte' style={{ fontWeight: 'bold' }}>CAPITAL</span>
                                </Typography>
                            </Toolbar>
                        </AppBar>
                    </Box>
                   {children}
                </Grid>
          </SessionAuthProvider>
      </body>
    </html>
  );
}
